import type { Metadata } from "next";
import localFont from 'next/font/local'
import "../globals.css";
import SessionProvider from "@/lib/SessionProvider";

import QueryProvider from "@/lib/QueryProvider";
import Navbar from "@/components/Navbar/Navbar";
import StoreProvider from "@/lib/redux/StoreProvider";
import { NextIntlClientProvider } from 'next-intl';



// Local "Sen" font (files are in public/fonts/Sen)
const sen = localFont({
  variable: "--font-sen",
  src: [
    // Use filesystem-relative paths so the compiler can resolve these files
    { path: "../../../public/fonts/Sen/static/Sen-Regular.ttf", weight: "400", style: "normal" },
    { path: "../../../public/fonts/Sen/static/Sen-Medium.ttf", weight: "500", style: "normal" },
    { path: "../../../public/fonts/Sen/static/Sen-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "../../../public/fonts/Sen/static/Sen-Bold.ttf", weight: "700", style: "normal" },
    { path: "../../../public/fonts/Sen/static/Sen-ExtraBold.ttf", weight: "800", style: "normal" },
    // Fallback to variable file if present
    { path: "../../../public/fonts/Sen/Sen-VariableFont_wght.ttf", weight: "100 900", style: "normal" },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>
};
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={` ${sen.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <SessionProvider >
            <QueryProvider >
              <StoreProvider>
                <Navbar />
                <main className="">
                  {children}
                </main>
              </StoreProvider>
            </QueryProvider>

          </SessionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
